apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-dotnet-app
  description: My .NET Core application
  annotations:
    backstage.io/docker-ref: my-dotnet-app
    backstage.io/container-image-name: my-dotnet-app
